### ISSUE TITLE
منظور از لایه؟

### ISSUE THREAD

**Issue by hosseinGanjyar** [motalebe/WeGramSharp#1]
سلام و خسته نباشید
ممنون میشم درباره لایه ها در تلگرام توضیحی میدادین.
ممنون

**Comment by motalebe** [comment]
سلام
منظور از لایه های تلگرام، شما های متدهاست ک تلگرام ارائه کرد. تا الان 18 لایه پایه و 68لایه زیرمجموعه ارائه داد. مستندات:
https://core.telegram.org/api/layers
