### ISSUE TITLE
شما در حال استفاده از نسخه‌ای از تلگرام هستید که دیگر پشتیبانی نمی‌شود و به زودی غیر‌فعال خواهد شد.

### ISSUE THREAD

**Issue by hamedsadeghi190** [motalebe/WeGramSharp#2]
سلام، H@M3D. شما در حال استفاده از نسخه‌ای از تلگرام هستید که دیگر پشتیبانی نمی‌شود و به زودی غیر‌فعال خواهد شد.
لطفا در اینجا به آخرین نسخه به روز رسانی نمایید:
https://telegram.org/upgrade/5

Hello, H@M3D. You are using a version of Telegram that is no longer supported and will be disabled soon. Please update to the latest version here:
https://telegram.org/upgrade/5

**Comment by motalebe** [comment]
سلام
مربوط به آی دی و هش درون برنامه هست ک برای تست قرار داده شد. با اپ آی دی و هش کد خودتون جایگزین کنید مشکل حل میشه
